#!/usr/bin/env python3
"""
Setup script for proofatlas.

This script configures tch-rs/libtorch linking before building the Rust extension.
It automatically creates .cargo/config.toml with the correct PyTorch library paths.
"""
import os
import shutil
import sys
from pathlib import Path

# Check for Rust toolchain
if not shutil.which('cargo'):
    print("""
Error: Rust toolchain not found.

Install Rust from https://rustup.rs/:

    curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh

Then restart your shell and try again.
""", file=sys.stderr)
    sys.exit(1)

# Set environment variable for tch-rs to find PyTorch's libtorch
os.environ.setdefault('LIBTORCH_USE_PYTORCH', '1')


def setup_cargo_config():
    """Create .cargo/config.toml with PyTorch lib paths for tch-rs linking."""
    try:
        import torch
        torch_lib = str(Path(torch.__path__[0]) / "lib")
    except ImportError:
        print("Warning: PyTorch not found, skipping cargo config generation")
        return

    project_root = Path(__file__).parent
    cargo_dir = project_root / ".cargo"
    config_path = cargo_dir / "config.toml"

    # Check if config already exists with correct path
    if config_path.exists():
        content = config_path.read_text()
        if torch_lib in content:
            return  # Already configured correctly

    cargo_dir.mkdir(exist_ok=True)

    config = f'''# Auto-generated by setup.py for tch-rs/libtorch linking
# Re-run pip install -e . after changing Python environments

[env]
LIBTORCH_USE_PYTORCH = "1"

[target.x86_64-unknown-linux-gnu]
rustflags = ["-C", "link-arg=-Wl,-rpath,{torch_lib}"]

[target.aarch64-unknown-linux-gnu]
rustflags = ["-C", "link-arg=-Wl,-rpath,{torch_lib}"]

[target.x86_64-apple-darwin]
rustflags = ["-C", "link-arg=-Wl,-rpath,{torch_lib}"]

[target.aarch64-apple-darwin]
rustflags = ["-C", "link-arg=-Wl,-rpath,{torch_lib}"]
'''

    config_path.write_text(config)
    print(f"Created {config_path} with PyTorch lib: {torch_lib}")


def build_wasm():
    """Build the WASM package for the web interface."""
    import subprocess

    project_root = Path(__file__).parent
    wasm_crate = project_root / "crates" / "proofatlas-wasm"
    web_pkg = project_root / "web" / "pkg"

    # Check if wasm-pack is installed
    if not shutil.which('wasm-pack'):
        print("Installing wasm-pack...")
        try:
            subprocess.run(
                ["cargo", "install", "wasm-pack"],
                check=True,
                capture_output=True,
            )
        except subprocess.CalledProcessError as e:
            print(f"Warning: Failed to install wasm-pack: {e}")
            print("Web interface will not be available.")
            print("Install manually with: cargo install wasm-pack")
            return

    # Check if WASM crate exists
    if not (wasm_crate / "Cargo.toml").exists():
        print("Warning: proofatlas-wasm crate not found, skipping WASM build")
        return

    # Check if already built
    if (web_pkg / "proofatlas_wasm.js").exists():
        print("WASM package already built")
        return

    print("Building WASM package...")
    try:
        subprocess.run(
            ["wasm-pack", "build", "--target", "web", "--out-dir", str(web_pkg)],
            cwd=wasm_crate,
            check=True,
        )
        print(f"WASM package built: {web_pkg}")
    except subprocess.CalledProcessError as e:
        print(f"Warning: WASM build failed: {e}")
        print("Web interface will not be available.")


# Configure cargo before build
setup_cargo_config()

# Build WASM package
build_wasm()

# Import and run setuptools
from setuptools import setup

if __name__ == '__main__':
    setup()
