#!/usr/bin/env python3
"""
Setup script for proofatlas.

This script configures tch-rs/libtorch linking before building the Rust extension.
It automatically creates .cargo/config.toml with the correct PyTorch library paths.
"""
import os
import sys
from pathlib import Path

# Set environment variable for tch-rs to find PyTorch's libtorch
os.environ.setdefault('LIBTORCH_USE_PYTORCH', '1')


def setup_cargo_config():
    """Create .cargo/config.toml with PyTorch lib paths for tch-rs linking."""
    try:
        import torch
        torch_lib = str(Path(torch.__path__[0]) / "lib")
    except ImportError:
        print("Warning: PyTorch not found, skipping cargo config generation")
        return

    project_root = Path(__file__).parent
    cargo_dir = project_root / ".cargo"
    config_path = cargo_dir / "config.toml"

    # Check if config already exists with correct path
    if config_path.exists():
        content = config_path.read_text()
        if torch_lib in content:
            return  # Already configured correctly

    cargo_dir.mkdir(exist_ok=True)

    config = f'''# Auto-generated by setup.py for tch-rs/libtorch linking
# Re-run pip install -e . after changing Python environments

[env]
LIBTORCH_USE_PYTORCH = "1"

[target.x86_64-unknown-linux-gnu]
rustflags = ["-C", "link-arg=-Wl,-rpath,{torch_lib}"]

[target.aarch64-unknown-linux-gnu]
rustflags = ["-C", "link-arg=-Wl,-rpath,{torch_lib}"]

[target.x86_64-apple-darwin]
rustflags = ["-C", "link-arg=-Wl,-rpath,{torch_lib}"]

[target.aarch64-apple-darwin]
rustflags = ["-C", "link-arg=-Wl,-rpath,{torch_lib}"]
'''

    config_path.write_text(config)
    print(f"Created {config_path} with PyTorch lib: {torch_lib}")


# Configure cargo before build
setup_cargo_config()

# Import and run setuptools
from setuptools import setup

if __name__ == '__main__':
    setup()
