#!/usr/bin/env python3
"""Configure Cargo for tch-rs builds with PyTorch.

This script creates .cargo/config.toml with:
- LIBTORCH_USE_PYTORCH=1 for build-time PyTorch detection
- rpath settings so binaries can find libtorch at runtime

Run this after activating your Python environment with PyTorch installed.
"""

import sys
from pathlib import Path


def get_torch_lib_path() -> str:
    """Get the path to PyTorch's lib directory."""
    try:
        import torch
        return str(Path(torch.__path__[0]) / "lib")
    except ImportError:
        print("Error: PyTorch not found. Install it with: pip install torch", file=sys.stderr)
        sys.exit(1)


def main():
    project_root = Path(__file__).parent.parent
    cargo_dir = project_root / ".cargo"
    config_path = cargo_dir / "config.toml"

    torch_lib = get_torch_lib_path()

    # Create .cargo directory if needed
    cargo_dir.mkdir(exist_ok=True)

    # Generate config.toml
    config = f'''# Auto-generated by scripts/setup_cargo.py
# Re-run after changing Python environments

[env]
LIBTORCH_USE_PYTORCH = "1"

[target.x86_64-unknown-linux-gnu]
rustflags = ["-C", "link-arg=-Wl,-rpath,{torch_lib}"]

[target.aarch64-unknown-linux-gnu]
rustflags = ["-C", "link-arg=-Wl,-rpath,{torch_lib}"]

[target.x86_64-apple-darwin]
rustflags = ["-C", "link-arg=-Wl,-rpath,{torch_lib}"]

[target.aarch64-apple-darwin]
rustflags = ["-C", "link-arg=-Wl,-rpath,{torch_lib}"]
'''

    config_path.write_text(config)
    print(f"Created {config_path}")
    print(f"PyTorch lib: {torch_lib}")
    print()
    print("You can now build with: cargo build")


if __name__ == "__main__":
    main()
